//! End-to-end agent spending flow.
//!
//! Deploys all eight workspace contracts into one mock Soroban [`Env`] and
//! exercises the full lifecycle of an agent spend:
//!
//! 1. `initialize` the registry and register the organization.
//! 2. Deploy treasury, budget, policy, wallet and escrow; register their
//!    addresses in the registry under the organization.
//! 3. Mint a real SAC token and fund the treasury.
//! 4. Create a wallet for the org's owner and give the agent the Agent role.
//! 5. Allocate a budget and register a policy that caps agent spending.
//! 6. Move value: treasury → wallet → (policy/budget-gated spend) → escrow.
//! 7. Assert token balances and contract state at every step, including
//!    constraint violations: policy denial, budget exhaustion, unauthorized
//!    multisig execution and unauthorized escrow release.
//!
//! The client wrappers generated by the Soroban SDK unwrap `Result`s
//! internally (panicking on error), so the violation tests use `try_*`
//! variants and assert on the deterministic [`Error`] codes.

use astroid_budget::{BudgetContract, BudgetContractClient, Period};
use astroid_escrow::{EscrowContract, EscrowContractClient, EscrowState};
use astroid_policy::{PolicyContract, PolicyContractClient};
use astroid_proposal::{ProposalContract, ProposalContractClient, ProposalState};
use astroid_registry::{RegistryContract, RegistryContractClient};
use astroid_shared::errors::Error;
use astroid_shared::types::{AssetAmount, ModuleKind, ResourceState};
use astroid_treasury::{TreasuryContract, TreasuryContractClient};
use astroid_wallet::access::Role;
use astroid_wallet::{WalletContract, WalletContractClient};
use soroban_sdk::{
    testutils::{Address as _, Ledger},
    token, vec, Address, BytesN, Env, String, Vec,
};

const START: u64 = 1_000;
/// The treasury hard-codes the policy id `"active"` on every spend gate.
const POLICY_ID: &str = "active";
const BUDGET_ID: &str = "agent-daily";
const ORG: &str = "acme";

/// All eight contracts deployed into one `Env`, wired like the real protocol.
struct Harness<'a> {
    env: Env,
    registry: RegistryContractClient<'a>,
    treasury: TreasuryContractClient<'a>,
    budget: BudgetContractClient<'a>,
    policy: PolicyContractClient<'a>,
    wallet: WalletContractClient<'a>,
    escrow: EscrowContractClient<'a>,
    /// Address standing in for the multisig/proposal governance layer.
    multisig: Address,
    admin: Address,
    org_owner: Address,
    agent: Address,
    recipient: Address,
    asset: Address,
}

/// Deploy every workspace contract in dependency order, register the org's
/// module addresses with the registry, and fund the treasury.
fn setup() -> Harness<'static> {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().with_mut(|l| l.timestamp = START);

    let admin = Address::generate(&env);
    let org_owner = Address::generate(&env);
    let agent = Address::generate(&env);
    let recipient = Address::generate(&env);
    let multisig = Address::generate(&env);

    // 1. Registry — source of truth for module addresses.
    let registry_id = env.register_contract(None, RegistryContract);
    let registry = RegistryContractClient::new(&env, &registry_id);
    registry.initialize(&admin);
    registry.register_org(&admin, &String::from_str(&env, ORG), &org_owner);

    // 2. Treasury — custodies org funds. The multisig is recorded so the
    //    emergency freeze path has a counterparty.
    let treasury_id = env.register_contract(None, TreasuryContract);
    let treasury = TreasuryContractClient::new(&env, &treasury_id);
    treasury.initialize(&String::from_str(&env, ORG), &admin);
    treasury.set_multisig(&admin, &multisig);

    // 3. Budget — spending limits consumed by the treasury.
    let budget_id = env.register_contract(None, BudgetContract);
    let budget = BudgetContractClient::new(&env, &budget_id);
    budget.initialize(&admin);

    // 4. Policy — rule engine consulted before every spend.
    let policy_id = env.register_contract(None, PolicyContract);
    let policy = PolicyContractClient::new(&env, &policy_id);
    policy.initialize();

    // 5. Wallet — per-org custody with role-based access.
    let wallet_id = env.register_contract(None, WalletContract);
    let wallet = WalletContractClient::new(&env, &wallet_id);
    wallet.initialize(&admin);

    // 6. Escrow — time-locked conditional custody.
    let escrow_id = env.register_contract(None, EscrowContract);
    let escrow = EscrowContractClient::new(&env, &escrow_id);
    escrow.initialize();

    // 7. Multisig + proposal — deployed and recorded in the registry like the
    //    other modules; governance flows in these tests act through the
    //    admin/owner roles directly.
    let multisig_contract = env.register_contract(None, astroid_multisig::MultiSigContract);
    let proposal_contract = env.register_contract(None, astroid_proposal::ProposalContract);
    registry.register_module(
        &admin,
        &String::from_str(&env, ORG),
        &ModuleKind::Multisig,
        &multisig_contract,
    );
    registry.register_module(
        &admin,
        &String::from_str(&env, ORG),
        &ModuleKind::Proposal,
        &proposal_contract,
    );

    // 8. Register the org's core modules so `lookup` resolves them.
    registry.register_module(
        &admin,
        &String::from_str(&env, ORG),
        &ModuleKind::Treasury,
        &treasury_id,
    );
    registry.register_module(
        &admin,
        &String::from_str(&env, ORG),
        &ModuleKind::Wallet,
        &wallet_id,
    );
    registry.register_module(
        &admin,
        &String::from_str(&env, ORG),
        &ModuleKind::Budget,
        &budget_id,
    );
    registry.register_module(
        &admin,
        &String::from_str(&env, ORG),
        &ModuleKind::Policy,
        &policy_id,
    );
    registry.register_module(
        &admin,
        &String::from_str(&env, ORG),
        &ModuleKind::Escrow,
        &escrow_id,
    );

    // 9. A real SAC token the whole flow moves around.
    let token_admin = Address::generate(&env);
    let asset = env
        .register_stellar_asset_contract_v2(token_admin)
        .address();

    // 10. Treasury wiring: asset whitelist plus the budget link. The policy
    //     link is deliberately NOT wired here — the treasury consults the
    //     policy on every withdrawal once it is set, so each test opts in via
    //     [`wire_policy`] to exercise the gate it cares about.
    treasury.add_approved_asset(&admin, &asset);
    treasury.set_budget(&admin, &budget_id);

    // Mint the funding pool to the admin, then deposit into the treasury.
    token::StellarAssetClient::new(&env, &asset).mint(&admin, &1_000_000);
    treasury.deposit(&admin, &asset, &500_000);

    Harness {
        env,
        registry,
        treasury,
        budget,
        policy,
        wallet,
        escrow,
        multisig,
        admin,
        org_owner,
        agent,
        recipient,
        asset,
    }
}

fn token_balance(h: &Harness, who: &Address) -> i128 {
    token::TokenClient::new(&h.env, &h.asset).balance(who)
}

fn string(h: &Harness, s: &str) -> String {
    String::from_str(&h.env, s)
}

/// Wire the policy contract into the treasury so every treasury withdrawal
/// is policy-gated through the org-wide `"active"` policy id.
fn wire_policy(h: &Harness) {
    h.treasury.set_policy(&h.admin, &h.policy.address);
}

/// Register the org-wide `"active"` policy: at most `max_amount` per spend,
/// only in `asset`, and — when `recipient_only` is set — only to `recipient`.
fn register_active_policy(h: &Harness, max_amount: i128, recipient_only: bool) {
    h.policy.register_policy(
        &h.admin,
        &string(h, POLICY_ID),
        &BytesN::from_array(&h.env, &[0u8; 32]),
        &max_amount,
        &if recipient_only {
            Some(h.recipient.clone())
        } else {
            None
        },
        &Some(h.asset.clone()),
        &0u64,
    );
}

/// Create the owner's wallet, grant `agent` the Agent role, and fund the
/// wallet with `amount` from the treasury.
///
/// No policy is registered when this helper runs, so the treasury funding
/// withdrawal is ungated — the policy gate is switched on afterwards for the
/// agent-facing spends each test cares about.
fn fund_agent_wallet(h: &Harness, amount: i128) -> u64 {
    let wallet_id = h.wallet.create_wallet(&h.org_owner);
    h.wallet
        .grant_role(&h.org_owner, &wallet_id, &h.agent, &Role::Agent);
    h.treasury
        .withdraw(&h.admin, &h.asset, &h.wallet.address, &amount);
    h.wallet
        .deposit(&wallet_id, &h.treasury.address, &h.asset, &amount);
    wallet_id
}

/// Happy path: org setup → treasury funding → agent wallet → gated spend →
/// escrow custody. Asserts balances and state transitions at every step.
#[test]
fn full_agent_spending_flow_end_to_end() {
    let h = setup();

    // --- Wallet creation and role delegation -------------------------------
    let wallet_id = h.wallet.create_wallet(&h.org_owner);
    assert_eq!(h.wallet.get_wallet(&wallet_id).owner, h.org_owner);
    assert_eq!(h.wallet.get_wallet(&wallet_id).state, ResourceState::Active);
    h.wallet
        .grant_role(&h.org_owner, &wallet_id, &h.agent, &Role::Agent);
    assert_eq!(h.wallet.get_role(&wallet_id, &h.agent), Some(Role::Agent));

    // --- Budget + policy for the agent -------------------------------------
    // One-shot budget envelope owned by the treasury admin.
    h.budget.allocate(
        &h.admin,
        &string(&h, BUDGET_ID),
        &50_000,
        &Period::None,
        &false,
        &0u64,
    );
    let budget = h.budget.get(&string(&h, BUDGET_ID));
    assert_eq!(budget.limit, 50_000);
    assert_eq!(budget.spent, 0);

    // --- Treasury → wallet funding ------------------------------------------
    // No policy is registered yet, so the funding withdrawal is ungated.
    h.treasury
        .withdraw(&h.admin, &h.asset, &h.wallet.address, &30_000);
    // The internal treasury accounting moved value out.
    let holding = h.treasury.holding(&h.asset);
    assert_eq!(holding.total_in, 500_000 - 30_000);
    assert_eq!(holding.total_out, 30_000);
    // The wallet custodies the funds internally.
    h.wallet
        .deposit(&wallet_id, &h.treasury.address, &h.asset, &30_000);
    assert_eq!(h.wallet.balance(&wallet_id, &h.asset), 30_000);

    // --- Policy gate is switched on for agent-facing spends -----------------
    // The org-wide policy now allows at most 10_000 per spend, only to
    // `recipient` in `asset` — exactly the agent's settlement payment.
    wire_policy(&h);
    register_active_policy(&h, 10_000, true);

    // --- Agent spend inside policy and budget limits ------------------------
    let recipient_before = token_balance(&h, &h.recipient);
    h.wallet
        .transfer(&h.agent, &wallet_id, &h.recipient, &h.asset, &5_000);
    assert_eq!(token_balance(&h, &h.recipient), recipient_before + 5_000);
    assert_eq!(h.wallet.balance(&wallet_id, &h.asset), 25_000);

    // --- Fund an escrow from the wallet's remaining funds -------------------
    // The escrow is funded from the treasury to the wallet's custodial
    // address so the internal wallet bookkeeping stays consistent.
    let escrow_assets: Vec<AssetAmount> = vec![
        &h.env,
        AssetAmount {
            asset: h.asset.clone(),
            amount: 10_000,
        },
    ];
    let escrow_id = h.escrow.create(
        &h.treasury.address,
        &h.recipient,
        &h.admin,
        &escrow_assets,
        &(START + 86_400),
        &0u64,
        &string(&h, "agent settlement"),
        &Vec::new(&h.env),
        &0u32,
    );
    assert_eq!(h.escrow.get(&escrow_id).state, EscrowState::Funded);
    // The escrow holds the full amount in real custody.
    assert_eq!(token_balance(&h, &h.escrow.address), 10_000);

    // --- Arbiter releases the escrow to the recipient ------------------------
    h.escrow.release(&h.admin, &escrow_id, &10_000);
    assert_eq!(h.escrow.get(&escrow_id).state, EscrowState::Released);
    assert_eq!(
        token_balance(&h, &h.recipient),
        recipient_before + 5_000 + 10_000
    );
    assert_eq!(token_balance(&h, &h.escrow.address), 0);

    // --- Registry lookups resolve every module ------------------------------
    for (kind, addr) in [
        (ModuleKind::Treasury, h.treasury.address.clone()),
        (ModuleKind::Wallet, h.wallet.address.clone()),
        (ModuleKind::Escrow, h.escrow.address.clone()),
    ] {
        assert_eq!(h.registry.lookup(&string(&h, ORG), &kind), addr);
    }
    assert!(h.registry.verify_owner(&string(&h, ORG), &h.org_owner));
}

/// The treasury refuses to move funds to a recipient the policy denies.
#[test]
fn policy_denial_blocks_treasury_withdrawal() {
    let h = setup();

    // Policy allows spending only to `recipient`.
    wire_policy(&h);
    register_active_policy(&h, 10_000, true);

    let stranger = Address::generate(&h.env);
    let res = h
        .treasury
        .try_withdraw(&h.admin, &h.asset, &stranger, &1_000);
    assert_eq!(res, Err(Ok(Error::PolicyDenied)));
    // Nothing moved.
    assert_eq!(h.treasury.holding(&h.asset).total_out, 0);
    assert_eq!(token_balance(&h, &stranger), 0);
}

/// An empty budget envelope cannot absorb any spend.
#[test]
fn budget_exhaustion_blocks_treasury_withdrawal() {
    let h = setup();

    // Open policy so only the budget gate can reject the spend.
    wire_policy(&h);
    register_active_policy(&h, 100_000, false);

    // A budget envelope attached to the asset holding, exhausted by an
    // earlier spend.
    h.budget.allocate(
        &h.admin,
        &string(&h, BUDGET_ID),
        &1i128,
        &Period::None,
        &false,
        &0u64,
    );
    h.treasury
        .allocate_budget(&h.admin, &h.asset, &string(&h, BUDGET_ID));
    h.budget.consume(&h.admin, &string(&h, BUDGET_ID), &1i128);
    let budget = h.budget.get(&string(&h, BUDGET_ID));
    assert_eq!(budget.spent, 1);
    assert_eq!(budget.limit, 1);

    // The spend is within the treasury balance but the attached budget
    // envelope is empty, so the budget contract rejects the debit.
    let res = h
        .treasury
        .try_withdraw(&h.admin, &h.asset, &h.recipient, &1_000);
    assert_eq!(res, Err(Ok(Error::BudgetExceeded)));
    assert_eq!(h.treasury.holding(&h.asset).total_out, 0);
    assert_eq!(token_balance(&h, &h.recipient), 0);
}

/// Only the wallet owner (Admin role) may withdraw from a wallet; an agent
/// cannot pull funds out for itself, and governance addresses without a role
/// have no spending power either.
#[test]
fn unauthorized_execution_is_rejected_end_to_end() {
    let h = setup();

    let wallet_id = h.wallet.create_wallet(&h.org_owner);
    h.treasury
        .withdraw(&h.admin, &h.asset, &h.wallet.address, &10_000);
    h.wallet
        .deposit(&wallet_id, &h.treasury.address, &h.asset, &10_000);

    // An unprivileged principal is not authorized at the governance level.
    let intruder = Address::generate(&h.env);
    let res = h
        .wallet
        .try_withdraw(&intruder, &wallet_id, &h.asset, &5_000);
    assert_eq!(res, Err(Ok(Error::Unauthorized)));
    assert_eq!(h.wallet.balance(&wallet_id, &h.asset), 10_000);
    assert_eq!(token_balance(&h, &intruder), 0);

    // The multisig address standing in for governance: without a role on the
    // wallet it has no spending power either.
    let res = h
        .wallet
        .try_withdraw(&h.multisig, &wallet_id, &h.asset, &5_000);
    assert_eq!(res, Err(Ok(Error::Unauthorized)));
    assert_eq!(h.wallet.balance(&wallet_id, &h.asset), 10_000);

    // An agent may transfer out, but never withdraw to the owner.
    h.wallet
        .grant_role(&h.org_owner, &wallet_id, &h.agent, &Role::Agent);
    let res = h
        .wallet
        .try_withdraw(&h.agent, &wallet_id, &h.asset, &5_000);
    assert_eq!(res, Err(Ok(Error::Unauthorized)));
    assert_eq!(h.wallet.balance(&wallet_id, &h.asset), 10_000);
}

/// Escrow release is arbiter-gated and escrow custody is time-locked: funds
/// come back to the sender once the deadline passes without fulfillment.
#[test]
fn escrow_constraints_are_enforced_end_to_end() {
    let h = setup();

    let wallet_id = fund_agent_wallet(&h, 20_000);

    // Fund the escrow straight from the treasury, which custodies the funds
    // until the escrow conditions resolve.
    let escrow_assets: Vec<AssetAmount> = vec![
        &h.env,
        AssetAmount {
            asset: h.asset.clone(),
            amount: 10_000,
        },
    ];
    let escrow_id = h.escrow.create(
        &h.treasury.address,
        &h.recipient,
        &h.admin,
        &escrow_assets,
        &(START + 86_400),
        &0u64,
        &string(&h, "gated settlement"),
        &Vec::new(&h.env),
        &0u32,
    );
    assert_eq!(token_balance(&h, &h.escrow.address), 10_000);

    // 1. A random principal cannot release escrowed funds.
    let intruder = Address::generate(&h.env);
    let res = h.escrow.try_release(&intruder, &escrow_id, &10_000);
    assert_eq!(res, Err(Ok(Error::Unauthorized)));

    // 2. Even the legit arbiter cannot release past the deadline.
    h.env.ledger().with_mut(|l| l.timestamp = START + 100_000);
    let res = h.escrow.try_release(&h.admin, &escrow_id, &10_000);
    assert_eq!(res, Err(Ok(Error::EscrowExpired)));
    assert_eq!(h.escrow.get(&escrow_id).state, EscrowState::Funded);

    // 3. The sender claws the funds back after the deadline + grace.
    h.escrow.refund(&h.treasury.address, &escrow_id);
    assert_eq!(h.escrow.get(&escrow_id).state, EscrowState::Refunded);
    assert_eq!(token_balance(&h, &h.escrow.address), 0);
    assert_eq!(h.wallet.balance(&wallet_id, &h.asset), 20_000);
}

/// Time-locked escrow custody: the beneficiary cannot withdraw before the
/// unlock time, only after maturity.
#[test]
fn timelocked_escrow_payout_across_the_workflow() {
    let h = setup();

    let _wallet_id = fund_agent_wallet(&h, 20_000);

    let unlock_time = START + 5_000;
    let escrow_assets: Vec<AssetAmount> = vec![
        &h.env,
        AssetAmount {
            asset: h.asset.clone(),
            amount: 15_000,
        },
    ];
    let escrow_id = h.escrow.create_timelock(
        &h.treasury.address,
        &h.recipient,
        &h.admin,
        &escrow_assets,
        &unlock_time,
        &string(&h, "vesting payout"),
    );
    assert_eq!(h.escrow.get(&escrow_id).state, EscrowState::Funded);

    // Locked before maturity.
    h.env.ledger().with_mut(|l| l.timestamp = START + 2_500);
    assert_eq!(h.escrow.get_claimable_amount(&escrow_id), 0);
    let res = h.escrow.try_withdraw(&h.recipient, &escrow_id, &15_000);
    assert_eq!(res, Err(Ok(Error::TimeLockActive)));
    assert_eq!(token_balance(&h, &h.recipient), 0);

    // Claimable at maturity, in full.
    h.env.ledger().with_mut(|l| l.timestamp = unlock_time);
    assert_eq!(h.escrow.get_claimable_amount(&escrow_id), 15_000);
    let released = h.escrow.claim(&h.recipient, &escrow_id);
    assert_eq!(released, 15_000);
    assert_eq!(h.escrow.get(&escrow_id).state, EscrowState::Released);
    assert_eq!(token_balance(&h, &h.recipient), 15_000);
    assert_eq!(token_balance(&h, &h.escrow.address), 0);
}

/// The wallet's circuit breaker halts agent spending globally and the admin
/// restores it.
#[test]
fn emergency_breaker_halts_and_resumes_agent_spending() {
    let h = setup();

    let wallet_id = h.wallet.create_wallet(&h.org_owner);
    h.wallet
        .grant_role(&h.org_owner, &wallet_id, &h.agent, &Role::Agent);
    h.treasury
        .withdraw(&h.admin, &h.asset, &h.wallet.address, &10_000);
    h.wallet
        .deposit(&wallet_id, &h.treasury.address, &h.asset, &10_000);

    // Trip the breaker (admin doubles as guardian until one is designated).
    h.wallet.emergency_pause(&h.admin);
    assert!(h.wallet.is_paused());

    let res = h
        .wallet
        .try_transfer(&h.agent, &wallet_id, &h.recipient, &h.asset, &1_000);
    assert_eq!(res, Err(Ok(Error::WalletPaused)));
    assert_eq!(h.wallet.balance(&wallet_id, &h.asset), 10_000);

    // Creating new wallets is blocked too.
    let res = h.wallet.try_create_wallet(&h.org_owner);
    assert_eq!(res, Err(Ok(Error::WalletPaused)));

    // Only the admin resets the breaker; then spending resumes.
    h.wallet.emergency_unpause(&h.admin);
    assert!(!h.wallet.is_paused());
    h.wallet
        .transfer(&h.agent, &wallet_id, &h.recipient, &h.asset, &1_000);
    assert_eq!(h.wallet.balance(&wallet_id, &h.asset), 9_000);
    assert_eq!(token_balance(&h, &h.recipient), 1_000);
}

/// The treasury batch-pays several recipients in one atomic, policy-gated
/// transaction; a policy-violating leg rejects the whole batch.
#[test]
fn treasury_batch_payout_is_policy_gated_and_atomic() {
    let h = setup();

    // Open policy: capped per-spend, no recipient restriction.
    wire_policy(&h);
    register_active_policy(&h, 10_000, false);

    let payees = vec![
        &h.env,
        astroid_shared::types::Payment {
            recipient: Address::generate(&h.env),
            amount: 2_000,
        },
        astroid_shared::types::Payment {
            recipient: Address::generate(&h.env),
            amount: 3_000,
        },
    ];

    h.treasury
        .batch_transfer(&h.admin, &h.asset, &payees.clone());
    let holding = h.treasury.holding(&h.asset);
    assert_eq!(holding.total_out, 5_000);
    for p in payees.iter() {
        assert_eq!(token_balance(&h, &p.recipient), p.amount);
    }

    // A batch whose per-leg amount breaches the policy cap is rejected whole.
    let too_big = vec![
        &h.env,
        astroid_shared::types::Payment {
            recipient: Address::generate(&h.env),
            amount: 2_000,
        },
        astroid_shared::types::Payment {
            recipient: Address::generate(&h.env),
            amount: 20_000,
        },
    ];
    let res = h.treasury.try_batch_transfer(&h.admin, &h.asset, &too_big);
    assert_eq!(res, Err(Ok(Error::PolicyDenied)));
    // The accepted legs did not partially pay out.
    assert_eq!(token_balance(&h, &too_big.get(0).unwrap().recipient), 0);
    assert_eq!(token_balance(&h, &too_big.get(1).unwrap().recipient), 0);
    assert_eq!(h.treasury.holding(&h.asset).total_out, 5_000);
}

/// The registry stays the source of truth: every deployed module resolves
/// through `lookup`, and the org owner verifies.
#[test]
fn registry_links_the_deployed_modules() {
    let h = setup();

    let expected = [
        (ModuleKind::Treasury, h.treasury.address.clone()),
        (ModuleKind::Wallet, h.wallet.address.clone()),
        (ModuleKind::Budget, h.budget.address.clone()),
        (ModuleKind::Policy, h.policy.address.clone()),
        (ModuleKind::Escrow, h.escrow.address.clone()),
    ];
    for (kind, addr) in expected {
        assert_eq!(h.registry.lookup(&string(&h, ORG), &kind), addr);
    }
    assert!(h.registry.verify_owner(&string(&h, ORG), &h.org_owner));
}

// ---------------------------------------------------------------------------
// Proposal timelock enforcement (issue #295)
// ---------------------------------------------------------------------------

/// The deployed proposal contract enforces its timelock end to end: a
/// proposal that reaches the approval threshold may not be executed before
/// `approved_at + timelock` (premature attempts fail with the protocol-wide
/// [`Error::TimelockNotExpired`] code and change nothing), execution succeeds
/// exactly at the release instant, and the executed state is observable
/// through the contract's own views and the registry.
#[test]
fn proposal_timelock_gates_execution_end_to_end() {
    let h = setup();

    // The harness deployed the proposal contract and registered it in the
    // registry; resolve it through the registry like a real integrator.
    let proposal_id = h.registry.lookup(&string(&h, ORG), &ModuleKind::Proposal);
    let proposal = ProposalContractClient::new(&h.env, &proposal_id);

    // Configure a 100-second timelock (the contract is fresh in this env).
    proposal.initialize(&100);
    assert_eq!(h.env.ledger().timestamp(), START);

    let proposer = h.org_owner.clone();
    let approvers: Vec<Address> = vec![&h.env, h.admin.clone(), h.agent.clone(), proposer.clone()];
    let pid = proposal.create(
        &proposer,
        &string(&h, ORG),
        &string(&h, "wallet-1"),
        &string(&h, "policy-1"),
        &approvers,
        &vec![&h.env],
        &2,
        &Vec::new(&h.env),
        &(START + 30 * 86_400),
        &0,
    );

    // Pending before any vote.
    assert_eq!(proposal.state(&pid), ProposalState::Pending);

    // One approval is not enough for the threshold of 2 — still pending.
    proposal.approve(&h.admin, &pid);
    assert_eq!(proposal.state(&pid), ProposalState::Pending);

    // Reaching the threshold flips the state and stamps the timelock start.
    proposal.approve(&h.agent, &pid);
    assert_eq!(proposal.state(&pid), ProposalState::Approved);
    assert!(!proposal.is_executed(&pid));
    assert_eq!(proposal.get(&pid).approved_at, START);

    // Executing immediately — long before the timelock releases — is refused
    // with the deterministic code and leaves the proposal untouched.
    let res = proposal.try_execute(&proposer, &pid);
    assert_eq!(res, Err(Ok(Error::TimelockNotExpired)));
    assert_eq!(proposal.state(&pid), ProposalState::Approved);

    // One second before the release instant the gate is still closed.
    h.env.ledger().with_mut(|l| l.timestamp = START + 99);
    let res = proposal.try_execute(&proposer, &pid);
    assert_eq!(res, Err(Ok(Error::TimelockNotExpired)));
    assert_eq!(proposal.state(&pid), ProposalState::Approved);

    // At exactly `approved_at + timelock` the gate opens: the `can_execute`
    // view agrees with the entrypoint, and execution completes into the
    // terminal executed state.
    h.env.ledger().with_mut(|l| l.timestamp = START + 100);
    assert!(proposal.can_execute(&pid));
    proposal.execute(&proposer, &pid);
    assert_eq!(proposal.state(&pid), ProposalState::Executed);
    assert!(proposal.is_executed(&pid));
    // Execution is one-shot: the gate closes again behind the proposal.
    assert!(!proposal.can_execute(&pid));
}
